"use client";

import { useEffect, useMemo, useState } from "react";

const emptySettings = { maintenanceMode: false, languageDirection: "ltr", currencySymbol: "€", currencyPosition: "before", decimalSeparator: ".", decimalNumber: 2, dateFormat: "DD/MM/YYYY", timeZone: "Europe/Rome", defaultPages: {}, companyInfo: {}, smtp: { encryption: "tls", port: 587 }, googleAnalyticsCode: "", googleRecaptchaKey: "", googleRecaptchaSecret: "" };
const pageOptions = { search: ["", "Search"], privacyPolicy: ["", "Privacy Policy"], termsConditions: ["", "Terms and Conditions"], categories: ["", "Categories"], stores: ["", "Stores"], locations: ["", "Locations"] };
const dateFormats = ["DD/MM/YYYY", "MM/DD/YYYY", "YYYY/MM/DD", "DD-MM-YYYY", "MM-DD-YYYY", "YYYY-MM-DD", "DD.MM.YYYY", "MM.DD.YYYY", "YYYY.MM.DD"];
const timeZones = typeof Intl !== "undefined" && Intl.supportedValuesOf ? Intl.supportedValuesOf("timeZone") : ["Europe/Rome", "UTC", "America/New_York", "Asia/Kolkata"];

function Field({ label, name, value, onChange, type = "text", placeholder = "" }) { return <div><label htmlFor={name} className="mb-1 block text-sm font-medium text-slate-700">{label}</label><input id={name} name={name} type={type} value={value ?? ""} onChange={onChange} placeholder={placeholder} className="w-full rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm text-slate-900 outline-none focus:border-accent focus:ring-2 focus:ring-accent/20" /></div>; }
function SelectField({ label, name, value, onChange, children }) { return <div><label htmlFor={name} className="mb-1 block text-sm font-medium text-slate-700">{label}</label><select id={name} name={name} value={value} onChange={onChange} className="w-full rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm text-slate-900 outline-none focus:border-accent focus:ring-2 focus:ring-accent/20">{children}</select></div>; }

export default function SettingsForm() {
  const [settings, setSettings] = useState(emptySettings); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [message, setMessage] = useState({ type: "", text: "" });
  useEffect(() => { fetch("/api/settings").then(async (response) => { const data = await response.json(); if (!response.ok) throw new Error(data.message || "Unable to load settings."); setSettings({ ...emptySettings, ...data.settings, defaultPages: { ...data.settings.defaultPages }, companyInfo: { ...data.settings.companyInfo }, smtp: { ...data.settings.smtp, password: "" } }); }).catch((error) => setMessage({ type: "error", text: error.message })).finally(() => setLoading(false)); }, []);
  const update = (event) => { const { name, value, type, checked } = event.target; setSettings((current) => ({ ...current, [name]: type === "checkbox" ? checked : value })); };
  const updateGroup = (group) => (event) => { const { name, value } = event.target; setSettings((current) => ({ ...current, [group]: { ...current[group], [name]: value } })); };
  const save = async (event) => { event.preventDefault(); setSaving(true); setMessage({ type: "", text: "" }); try { const response = await fetch("/api/settings", { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify(settings) }); const data = await response.json(); if (!response.ok) throw new Error(data.message || "Unable to save settings."); setMessage({ type: "success", text: data.message }); } catch (error) { setMessage({ type: "error", text: error.message }); } finally { setSaving(false); } };
  const currencyExample = useMemo(() => ({ before: `${settings.currencySymbol}0.00`, after: `0.00${settings.currencySymbol}`, "before-space": `${settings.currencySymbol} 0.00`, "after-space": `0.00 ${settings.currencySymbol}` }[settings.currencyPosition]), [settings.currencyPosition, settings.currencySymbol]);
  if (loading) return <div className="rounded-xl border border-slate-200 bg-white p-6 shadow-sm"><p className="text-sm text-slate-600">Loading settings...</p></div>;
  return <form onSubmit={save} className="space-y-6 rounded-xl border border-slate-200 bg-white p-6 shadow-sm">{message.text && <div className={`rounded-lg border px-4 py-3 text-sm ${message.type === "success" ? "border-green-200 bg-green-50 text-green-700" : "border-red-200 bg-red-50 text-red-700"}`}>{message.text}</div>}
    <section className="space-y-5"><h2 className="text-lg font-semibold text-slate-900">Site Settings</h2><div className="grid gap-5 md:grid-cols-2"><label className="flex items-center gap-3 text-sm text-slate-700"><input type="checkbox" name="maintenanceMode" checked={settings.maintenanceMode} onChange={update} />Maintenance Mode <span className="text-slate-500">{settings.maintenanceMode ? "Enabled" : "Disabled"}</span></label><SelectField label="Language Direction" name="languageDirection" value={settings.languageDirection} onChange={update}><option value="ltr">Left to Right (LTR)</option><option value="rtl">Right to Left (RTL)</option></SelectField><Field label="Currency Symbol" name="currencySymbol" value={settings.currencySymbol} onChange={update} /><SelectField label="Currency Position" name="currencyPosition" value={settings.currencyPosition} onChange={update}><option value="before">{currencyExample}</option><option value="after">0.00{settings.currencySymbol}</option><option value="before-space">{settings.currencySymbol} 0.00</option><option value="after-space">0.00 {settings.currencySymbol}</option></SelectField><SelectField label="Decimal Separator" name="decimalSeparator" value={settings.decimalSeparator} onChange={update}><option value=".">100.11</option><option value=",">100,11</option></SelectField><Field label="Decimal Number" name="decimalNumber" type="number" value={settings.decimalNumber} onChange={update} /><SelectField label="Date Format" name="dateFormat" value={settings.dateFormat} onChange={update}>{dateFormats.map((format) => <option key={format}>{format}</option>)}</SelectField><SelectField label="Time Zone" name="timeZone" value={settings.timeZone} onChange={update}>{timeZones.map((zone) => <option key={zone}>{zone}</option>)}</SelectField></div></section>
    <section className="space-y-5 border-t border-slate-200 pt-6"><h2 className="text-lg font-semibold text-slate-900">Default Pages</h2><div className="grid gap-5 md:grid-cols-2">{Object.entries(pageOptions).map(([name, [, label]]) => <SelectField key={name} label={label} name={name} value={settings.defaultPages[name] || ""} onChange={updateGroup("defaultPages")}><option value="">-</option><option value={name}>{label}</option></SelectField>)}</div></section>
    <section className="space-y-5 border-t border-slate-200 pt-6"><h2 className="text-lg font-semibold text-slate-900">Company Info</h2><div className="grid gap-5 md:grid-cols-2">{["facebook", "twitter", "youtube", "instagram", "linkedin", "whatsapp"].map((name) => <Field key={name} label={name[0].toUpperCase() + name.slice(1)} name={name} value={settings.companyInfo[name]} onChange={updateGroup("companyInfo")} />)}</div></section>
    <section className="space-y-5 border-t border-slate-200 pt-6"><h2 className="text-lg font-semibold text-slate-900">SMTP Configuration</h2><p className="text-sm text-slate-500">Recipient Email is where contact-form messages will be delivered.</p><div className="grid gap-5 md:grid-cols-2"><Field label="Recipient Email" name="recipientEmail" type="email" value={settings.smtp.recipientEmail} onChange={updateGroup("smtp")} /><Field label="Host" name="host" value={settings.smtp.host} onChange={updateGroup("smtp")} /><Field label="Email" name="email" type="email" value={settings.smtp.email} onChange={updateGroup("smtp")} /><Field label="Password" name="password" type="password" value={settings.smtp.password} onChange={updateGroup("smtp")} placeholder="Leave blank to keep current password" /><SelectField label="Encrypt" name="encryption" value={settings.smtp.encryption} onChange={updateGroup("smtp")}><option value="none">None</option><option value="ssl">SSL</option><option value="tls">TLS</option></SelectField><Field label="Port" name="port" type="number" value={settings.smtp.port} onChange={updateGroup("smtp")} /></div></section>
    <section className="space-y-5 border-t border-slate-200 pt-6"><h2 className="text-lg font-semibold text-slate-900">General</h2><Field label="Analytics / Tracking Code" name="googleAnalyticsCode" value={settings.googleAnalyticsCode} onChange={update} /><div className="grid gap-5 md:grid-cols-2"><Field label="Google Recaptcha Key" name="googleRecaptchaKey" value={settings.googleRecaptchaKey} onChange={update} /><Field label="Google Recaptcha Secret" name="googleRecaptchaSecret" type="password" value={settings.googleRecaptchaSecret} onChange={update} /></div></section>
    <div className="flex justify-end border-t border-slate-200 pt-6"><button type="submit" disabled={saving} className="rounded-lg bg-accent px-5 py-2.5 text-sm font-semibold text-white hover:bg-accent-hover disabled:opacity-50">{saving ? "Saving..." : "Save Settings"}</button></div>
  </form>;
}
